/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by scripts/compile-rules.ts
 */

import { RuleDefinition } from "../core/rules/rule-definition";

import { fireballRule } from "./spells/fireball.rule";

export const SPELLS_RULES: RuleDefinition[] = [fireballRule];

export const ALL_RULES: RuleDefinition[] = [...SPELLS_RULES];
