export enum ConflictType {
  STACKING = "STACKING",
  MUTUAL_EXCLUSION = "MUTUAL_EXCLUSION",
  PRIORITY_OVERRIDE = "PRIORITY_OVERRIDE",
  CANCEL_EFFECT = "CANCEL_EFFECT",
  REPLACE_EFFECT = "REPLACE_EFFECT",
}
