export enum ExecutionNode {
  ATTACK_ROLL = "ATTACK_ROLL",
  ATTACK_HIT_CHECK = "ATTACK_HIT_CHECK",
  DAMAGE_CALCULATION = "DAMAGE_CALCULATION",
  DAMAGE_MODIFIERS = "DAMAGE_MODIFIERS",
  DAMAGE_FINAL = "DAMAGE_FINAL",
  POST_DAMAGE = "POST_DAMAGE",
}
