export enum ExecutionNode {
  // Attack Lifecycle
  PRE_ATTACK_ROLL = "PRE_ATTACK_ROLL",
  ATTACK_ROLL = "ATTACK_ROLL",
  POST_ATTACK_ROLL = "POST_ATTACK_ROLL",
  ATTACK_HIT_CHECK = "ATTACK_HIT_CHECK",

  // Damage Lifecycle
  DAMAGE_CALCULATION = "DAMAGE_CALCULATION",
  DAMAGE_MODIFIERS = "DAMAGE_MODIFIERS",
  DAMAGE_FINAL = "DAMAGE_FINAL",
  POST_DAMAGE = "POST_DAMAGE",

  // Saving Throw Lifecycle
  SAVING_THROW_PRE_ROLL = "SAVING_THROW_PRE_ROLL",
  SAVING_THROW_ROLL = "SAVING_THROW_ROLL",
  POST_SAVING_THROW_ROLL = "POST_SAVING_THROW_ROLL",
  SAVING_THROW_CHECK = "SAVING_THROW_CHECK",
  POST_SAVING_THROW = "POST_SAVING_THROW",
}
