import fs from "node:fs";
import path from "node:path";

const RULES_DIR = path.join(__dirname, "../src/rules");
const GENERATED_FILE = path.join(RULES_DIR, "rules.generated.ts");

const DOMAINS = ["spells", "feats", "conditions", "class-features", "items"];

function compile() {
  console.log("[RuleCompiler] Starting compilation...");

  const allImports: string[] = [];
  const domainGroups: Record<string, string[]> = {};

  for (const domain of DOMAINS) {
    const domainDir = path.join(RULES_DIR, domain);
    if (!fs.existsSync(domainDir)) continue;

    domainGroups[domain] = [];
    const files = fs.readdirSync(domainDir);

    for (const file of files) {
      if (file.endsWith(".rule.ts")) {
        const ruleName = path.basename(file, ".rule.ts");
        const varName = `${ruleName}Rule`;

        allImports.push(
          `import { ${varName} } from "./${domain}/${ruleName}.rule";`,
        );
        domainGroups[domain].push(varName);
      }
    }
  }

  console.log(`[RuleCompiler] Found ${allImports.length} rules.`);

  let content = `/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by scripts/compile-rules.ts
 */

import { RuleDefinition } from "../core/rules/rule-definition";

${allImports.join("\n")}

`;

  const allVars: string[] = [];

  for (const domain of DOMAINS) {
    if (domainGroups[domain] && domainGroups[domain].length > 0) {
      const constName = `${domain.replace("-", "_").toUpperCase()}_RULES`;
      content += `export const ${constName}: RuleDefinition[] = [\n  ${domainGroups[domain].join(",\n  ")}\n];\n\n`;
      allVars.push(`...${constName}`);
    }
  }

  content += `export const ALL_RULES: RuleDefinition[] = [\n  ${allVars.join(",\n  ")}\n];\n`;

  fs.writeFileSync(GENERATED_FILE, content);
  console.log(`[RuleCompiler] Generated ${GENERATED_FILE}`);
}

compile();
