export const es = {
  character: {
    singular: "Personaje",
    plural: "Personajes",
    add: "Añadir personaje",
    input: "Nombre del personaje",
  },
  race: {
    singular: "Raza",
    input: "Selecciona una raza",
  },
  alignment: {
    singular: "Alineamiento",
    input: "Selecciona un alineamiento",
    lg: "Legal Bueno",
    ln: "Legal Neutral",
    le: "Legal Malvado",
    ng: "Neutral Bueno",
    n: "Neutral",
    ne: "Neutral Malvado",
    cg: "Caótico Bueno",
    cn: "Caótico Neutral",
    ce: "Caótico Malvado",
  },
  xp: {
    singular: "Puntos de experiencia",
  },
  class: {
    singular: "Clase",
    plural: "Clases",
    main: "Clase principal",
    add: "Añadir clase",
    input: "Selecciona una clase",
  },
  stats: {
    abilityScores: "Características",
    skills: "Habilidades",
    speed: "Velocidad",
  },
  savingThrows: {
    full: "Tiradas de salvación",
    death: "Tiradas de salvación de muerte",
    successes: "Éxitos",
    faliures: "Fallos",
  },
  pb: {
    full: "Bonificador de competencia",
    short: "BC",
  },
  hp: {
    full: "Puntos de golpe",
    short: "HP",
    total: "HP Total",
    temporal: "HP Temporal",
    hitDie: "Dados de golpe",
  },
  ac: {
    full: "Clase de armadura",
    short: "CA",
  },
  initiative: {
    full: "Iniciativa",
    bonus: "Bonus de iniciativa",
    order: "Orden de iniciativa",
  },
  rests: {
    long: "Descanso largo",
    short: "Descanso corto",
  },
  action: {
    accept: "Aceptar",
    confirm: "Confirmar",
    cancel: "Cancelar",
    close: "Cerrar",
    exit: "Salir",
    takenDamage: "Daño recibido",
    newTempHP: "Vida temporal nueva",
    receivedHealing: "Curación recibida",
    useHitDice: "Usar dados de golpe",
  },
} as const;
