export enum GameEvent {
  TURN_START,
  TURN_END,
  ATTACK_ROLL,
  ATTACK_HIT,
  ATTACK_MISS,
  DAMAGE_RECEIVED,
  DAMAGE_DEALT,
  SPELL_CAST,
  ENTER_AURA,
  EXIT_AURA,
  CONDITION_APPLIED,
  CONDITION_REMOVED,
}
