export enum GameEvent {
  TURN_START,
  TURN_END,
  ATTACK_ROLL,
  ATTACK_HIT,
  ATTACK_MISS,
  DAMAGE_RECEIVED,
  DAMAGE_DEALT,
  SPELL_CAST,
  ENTER_AURA,
  EXIT_AURA,
  ENTER_RANGE,
  EXIT_RANGE,
  CONDITION_APPLIED,
  CONDITION_REMOVED,
  D20_ROLL,

  // Combat Loop Events
  COMBAT_START,
  COMBAT_END,
  ROUND_START,
  ROUND_END,

  // State Management Events
  EFFECT_APPLIED,
  EFFECT_REMOVED,
  STATS_RECALCULATED,
  ENTITY_MOVED,
}
