import { GameLocalizationCategory } from "@/services/localization/game-localization.types";

export const four_elements_features_es: GameLocalizationCategory = {
  disciple_of_the_elements: {
    name: "Discípulo de los Elementos",
    description:
      "Aprendes disciplinas mágicas que emplean el poder de los cuatro elementos. Una disciplina requiere que gastes puntos ki cada vez que la usas. Conoces la disciplina de Sintonía Elemental y otra disciplina elemental de tu elección, que se detallan en la sección Disciplinas Elementales más abajo. Aprendes una disciplina elemental adicional de tu elección a los niveles 6, 11 y 17. Cuando aprendas una nueva disciplina elemental, puedes reemplazar una disciplina elemental que ya conozcas por otra. Algunas disciplinas elementales te permiten lanzar conjuros. Para las reglas generales sobre lanzamiento de conjuros debes ver el Capítulo 10. Para lanzar uno de estos conjuros utilizas su tiempo de lanzamiento y otras reglas, pero no necesitas emplear componentes materiales. Una vez que alcanzas el nivel 5 en esta clase, puedes gastar puntos ki adicionales para aumentar el nivel de un conjuro de disciplina elemental que lances, suponiendo que el conjuro tenga un efecto que mejora en niveles superiores, como por ejemplo el conjuro manos ardientes. El nivel del conjuro aumenta en 1 por cada punto ki adicional que gastes. Por ejemplo, si eres un monje de nivel 5 y usas Barrido de Cenizas para lanzar manos ardientes, puedes gastar 3 puntos ki para lanzarlo como un conjuro de nivel 2 (el coste base de la disciplina son 2 puntos ki más 1 adicional). El máximo número de puntos ki que puedes gastar para lanzar un conjuro de esta forma (incluyendo los puntos ki de su coste base y cualquier punto ki gastado de forma adicional para aumentar su nivel) es determinado por tu nivel de monje.",
  },
};
